org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.4
minecraft_version_range=[1.20.3, 1.21)
neo_version=20.4.237
neo_version_range=[20.3,)
loader_version_range=[2,)

mod_id=skullcraft
mod_name=Skull Craft
mod_license=MIT
mod_version=7.4.0
mod_authors=Liu Dongyu
mod_description=With this mod, you can make your head bigger, wider or longer. And also you can get a mob skull easier.