modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="skullcraft"
version="${file.jarVersion}"
displayName="Skull Craft"
logoFile="logo.png"
credits="Liu Dongyu"
authors="Hexagram"
description='''
With this mod, you can make your head bigger, wider or longer.

And also you can get a mob skull easier.
'''
[[dependencies.skullcraft]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.skullcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
